name: .NET Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x

      - name: Test
        run: dotnet test --verbosity detailed --diag:./logs/logs.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./logs
        if: always()
